### ISSUE TITLE
Error: Must provide two arguments: analysis set and number of runs. Execution halted

### ISSUE THREAD

**Issue by adamisntdead** [cmmid/covid-uk#2]
Hello,

Getting this error:

`Error: Must provide two arguments: analysis set and the number of runs. Execution halted`

It occurs after the build step,
![image](https://user-images.githubusercontent.com/17102600/78244462-97b46d80-74dd-11ea-8d0b-e106a97ab05b.png)

**Comment by nicholasdavies** [comment]
Hi Adam, thanks for raising this -- see the new README.
