### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by pnavaro** [cmmid/covid-uk#4]
Hello, this is not an issue but If you have some problems to run  this code like me. I succeed by using [miniconda](https://docs.conda.io/en/latest/miniconda.html).

You need to download this file
https://github.com/pnavaro/covid-uk/blob/master/conda/environment.yml

and type 
```
cd covid-uk
conda env create -f conda/environment.yml
conda activate covid-uk
Rscript UK.R 1 50
```

I hope it helps

Thanks for sharing this 

Pierre

**Comment by paultanger** [comment]
Very cool!  How long does it take to run?

**Comment by pnavaro** [comment]
18 hours !  (Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz)

**Comment by alex6092400** [comment]
Hello ! What kind of problems did you have when you ran the code for the first time ?

**Comment by pnavaro** [comment]
~~~
from corona.cpp:8:
covidm/model_v1/process.h:23:5: error: 'string' does not name a type
     string source_name;     // name of the above

covidm/model_v1/process.h:27:5: error: 'vector' does not name a type
     vector<unsigned int> ids;   // identifiers of sub-process compartments
~~~

**Comment by alex6092400** [comment]
I have the same problem and i tried your method but it doesn't work for me. I've installed miniconda, then i download your file, put it in the directory covid-uk-master and in the anaconda prompt i've typed what you said but i get:

> Collecting package metadata (repodata.json): failed

> CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/conda-forge/win-64/repodata.json>

> Elapsed: -

> An HTTP error occurred when trying to retrieve this URL.

> HTTP errors are often intermittent, and a simple retry will get you on your way.

> 'https://conda.anaconda.org/conda-forge/win-64'

**Comment by pnavaro** [comment]
It seems to be a network issue, here the steps:
```
cd covid-uk
conda env create -f environment.yml
conda activate covid-uk
Rscript UK.R 1 50
```

**Comment by alex6092400** [comment]
I've finally succeed !! But still doesn't work, i get this type of error:

`Error in inDL(x, as.logical(local), as.logical(now), ...) :
 unable to load shared object 'H:/Documents/covid-uk-master/covidm/build/sourceCpp-x86_64-w64-mingw32-1.0.4.6/sourcecpp_143c1f1831/sourceCpp_30.dll':
 LoadLibrary failure:  The specified module could not be found.
Calls: source ... source -> withVisible -> eval -> eval -> dyn.load -> inDL`

**Comment by pnavaro** [comment]
I think it is a problem with the compiler. I am not a Windows user but try this
```
conda update r-essentials -n covid-uk -c r
conda activate covid-uk
Rscript UK.R 1 50
```



```

**Comment by alex6092400** [comment]
I get this when i try `conda update r-essentials -n covid-uk -c r` : 

`
PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\Users\Admin\anaconda3\envs\covid-uk
  package name: r-essentials
`

**Comment by pnavaro** [comment]
Install sorry not update
```
conda install r-essentials -n covid-uk -c r
```

**Comment by alex6092400** [comment]
I get `Solving environment: failed with initial frozen solve. Retrying with flexible solve` and  `Solving environment : Found conflicts !`  and `UnsatisfiableError: The following specifications were found to be incompatible with a past
explicit spec that is not an explicit spec in this operation (r-stringr):`

**Comment by pnavaro** [comment]
Probably it was not a good idea to change the conda channel

~~~
conda install r-essentials -n covid-uk -c conda-forge 
~~~

I already went through this with a colleague. Unfortunately my solution doesn’t seem robust. 😅

**Comment by alex6092400** [comment]
I still get the LoadLibrary failure error... Maybe it is due to my system variables PATH ?

**Comment by pnavaro** [comment]
You can try to remove the directory `covidm/build/`  to force rebuild.

**Comment by alex6092400** [comment]
Still getting the same error...

**Comment by pnavaro** [comment]
It is an issue with Rcpp, did you try a simple command ?

```r
Rcpp::evalCpp("2+2")
```

**Comment by alex6092400** [comment]
I've just tried this and yes it works

**Comment by pnavaro** [comment]
Perhaps this https://stackoverflow.com/questions/52150491/error-in-indlx-as-logicallocal-as-logicalnow-unable-to-load-share

**Comment by pnavaro** [comment]
You can try to install  mingw-w64 but i am afraid some side effets could happen... 
Using conda is safer, perhaps you could find it with
```
conda search mingw
```
I am not sure

**Comment by alex6092400** [comment]
When i type `sessionInfo()` i get this : 
![Problem_2](https://user-images.githubusercontent.com/67373461/86052472-550c1e00-ba57-11ea-9548-42aff04741dd.PNG)

Maybe the problem is in not attached  packages ?

**Comment by pnavaro** [comment]
OK i have the R 3.6 and i try to upgrade to 4.0 and i get same error

in environment.yml file replace the pattern `conda-forge` by `r`

then deactivate the covid-uk env
```
conda deactivate
```
remove the covid-uk env
```
conda env remove -n covid-uk
```
recreate the covid-uk with the `r` channel
```
conda env create -f environment.yml
conda activate covid-uk
Rscript UK.R 1 50
```

**Comment by pnavaro** [comment]
Probably the `r` channel is more stable than `conda-forge` for R users. Sorry but it is late in France and i have to go. I hope it works 🤞

**Comment by alex6092400** [comment]
when i try to create i get this 

`Solving environment: failed

ResolvePackageNotFound:
  - r-qs
  - r-rcppgsl
  - nlopt
`

**Comment by alex6092400** [comment]
no problem ! are you french ? Me too !

**Comment by pnavaro** [comment]
I uploaded a new version of  https://github.com/pnavaro/covid-uk/blob/master/conda/environment.yml
You can try it
```
condo activate covid-uk
conda env update -f environment.yml
```

**Comment by alex6092400** [comment]
it works !! Thank you so much !! I have some issues with the UK-view.R but i hope i will fix it !
